FROM tomcat:9-alpine
MAINTAINER Mark Ronald Delos Santos(markrdelossantos@hotmail.com)

COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY manager.xml /usr/local/tomcat/conf/Catalina/localhost/manager.xml