version: '2'
services:
  tomcat:
    build: ./java-restful-api/docker-files
    ports:
     - "8888:8080"
  frontend:
    build: ./react-frontend/
    ports:
     - "8080:8080"
    volumes:
      # OFFICE 
      # - /c/Users/madelos/DockerForDevs/react-frontend:/app
      # BAHAY
       - /d/DockerForDevs/react-frontend:/app
    # links:
    #   - redis
  nginx:
    image: nginx:1.11-alpine
    volumes:
      # - /c/Users/madelos/DockerForDevs/nginx:/conf:ro
      - /d/DockerForDevs/nginx:/conf:ro
    links:
      - frontend
    ports:
      - "9999:9999"
    entrypoint: nginx -c /conf/docker.conf
  redis:
    image: redis:3.2.5-alpine