version: '2'
services:
  tomcat:
    build: ./java-restful-api/docker-files
    ports:
     - "8888:8080"
  frontend:
    build: ./react-frontend/
    ports:
      - "80:8080"
    volumes:
      - /C_DRIVE/Presentation/DockerForDevs/react-frontend/app:/app