version: '2'
services:
  # tomcat:
  #   build: ./java-restful-api/docker-files
  #   ports:
  #    - "8888:8080"
  frontend:
    build: ./react-frontend/
    ports:
      - "80:80"
    volumes:
      # OFFICE 
      # - /c/Users/madelos/DockerForDevs/react-frontend:/app
      # BAHAY
       - /d/DockerForDevs/react-frontend:/app