version: '2'
services:
  # tomcat:
  #   build: ./java-restful-api/docker-files
  #   ports:
  #    - "8888:8080"
  frontend:
    build: ./react-frontend/
    ports:
      - "8080:8080"
    volumes:
      - /c/Users/madelos/DockerForDevs/react-frontend:/app